# Generated by Django 3.0.4 on 2020-03-12 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalcMeasure',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CalcHscode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Код ТНВЭД:')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование товарной позиции')),
                ('rate', models.CharField(max_length=255, verbose_name='Код ТНВЭД:\tНаименование товарной позиции\tСтавка ввозной таможенной пошлины')),
                ('measureCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.CalcMeasure')),
            ],
        ),
    ]
