# Generated by Django 3.0.4 on 2020-03-19 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200319_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagesite',
            name='title',
        ),
    ]
