# Generated by Django 3.0.4 on 2020-03-20 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_imagesite_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagesite',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
